spring.application.name=ecommerceapp

# H2 Console
spring.h2.console.enabled=true

# File based DB
spring.datasource.url=jdbc:h2:file:./data/ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# assets folder
project.product.images=images/product/

# File Upload validation
project.files.maxsize=5242880  # 5MB in bytes (or use smaller value like 2097152 for 2MB)

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update