spring.application.name=ecommerceapp

# H2 Console
spring.h2.console.enabled=true

# File based DB
spring.datasource.url=jdbc:h2:file:./data/ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update